---
- name: create paths and copy files
  block:
    - name: create paths
      file:
        path: "{{ item.1.dest | dirname }}"
        state: directory
      become: yes
      become_user: "{{ item.0.user }}"
      with_nested:
        - "{{ users }}"
        - "{{ role_copy }}"
      tags:
        - create_paths

    - name: copy files
      copy:
        src: "{{ item.1.src }}"
        dest: "{{ item.1.dest }}"
        mode: preserve
      become: yes
      become_user: "{{ item.0.user }}"
      with_nested:
        - "{{ users }}"
        - "{{ role_copy }}"
      tags:
        - copy_files

  tags:
    - setup
