---
- name: create paths and copy files
  block:
    - name: create paths
      file:
        path: "{{ item.1.dest | dirname }}"
        state: directory
      become: yes
      become_user: "{{ item.0.user }}"
      with_nested:
        - "{{ users }}"
        - "{{ role_download }}"
      tags:
        - create_paths

    - name: download
      get_url:
        url: "{{ item.1.src }}"
        dest: "{{ item.1.dest }}"
        checksum: "{{ item.1.checksum }}"
      become: yes
      become_user: "{{ item.0.user }}"
      with_nested:
        - "{{ users }}"
        - "{{ role_download }}"
      tags:
        - download
